window.produtos = [
  {
    "id": 1,
    "nome": "Flamengo I 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Flamengo 25/26. Listras rubro-negras clássicas. Tecido Aeroready.",
    "badge": "Mais Vendido",
    "imgs": ["Flamengo I 25/26_foto1.jpg"]
  },
  {
    "id": 2,
    "nome": "Flamengo II 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa reserva Flamengo 25/26. Branca com detalhes dourados.",
    "badge": "",
    "imgs": ["Flamengo II 25/26_foto1.jpg"]
  },
  {
    "id": 3,
    "nome": "Cruzeiro I 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Cruzeiro 25/26. Azul celeste clássica.",
    "badge": "Promoção",
    "imgs": ["Cruzeiro I 25/26_foto1.jpg"]
  },
  {
    "id": 4,
    "nome": "Corinthians I 25/26",
    "marca": "nike",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Corinthians 25/26. Branca com detalhes pretos. Dri-FIT ADV.",
    "badge": "Novo",
    "imgs": ["Corinthians I 25/26_foto1.jpg"]
  },
  {
    "id": 5,
    "nome": "Corinthians II 25/26",
    "marca": "nike",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa reserva Corinthians 25/26. Preta edição especial.",
    "badge": "",
    "imgs": ["Corinthians II 25/26_foto1.jpg"]
  },
  {
    "id": 6,
    "nome": "São Paulo I 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular São Paulo 25/26. Tricolor clássica.",
    "badge": "",
    "imgs": ["São Paulo I 25/26_foto1.jpg"]
  },
  {
    "id": 7,
    "nome": "Palmeiras I 25/26",
    "marca": "puma",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Palmeiras 25/26. Verde alviverde.",
    "badge": "",
    "imgs": ["Palmeiras I 25/26_foto1.jpg"]
  },
  {
    "id": 8,
    "nome": "Internacional I 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "Brasileirão",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Internacional 25/26. Vermelho colorado.",
    "badge": "Promoção",
    "imgs": ["Internacional I 25/26_foto1.jpg"]
  },
  {
    "id": 9,
    "nome": "Arsenal I 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "Premier League",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Arsenal 25/26. Vermelho gunners clássico.",
    "badge": "Mais Vendido",
    "imgs": ["Arsenal I 25/26_foto1.jpg"]
  },
  {
    "id": 10,
    "nome": "Real Madrid I 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "La Liga",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Real Madrid 25/26. Branca merengue clássica.",
    "badge": "",
    "imgs": ["Real Madrid I 25/26_foto1.jpg"]
  },
  {
    "id": 11,
    "nome": "FC Barcelona I 25/26",
    "marca": "nike",
    "tipo": "camisa de time",
    "liga": "La Liga",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Barcelona 25/26. Listras blaugrana. Dri-FIT ADV.",
    "badge": "Promoção",
    "imgs": ["FC Barcelona I 25/26_foto1.jpg"]
  },
  {
    "id": 12,
    "nome": "Manchester City I 25/26",
    "marca": "puma",
    "tipo": "camisa de time",
    "liga": "Premier League",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Manchester City 25/26. Azul celeste sky blue.",
    "badge": "",
    "imgs": ["Manchester City I 25/26_foto1.jpg"]
  },
  {
    "id": 13,
    "nome": "Liverpool I 25/26",
    "marca": "nike",
    "tipo": "camisa de time",
    "liga": "Premier League",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Liverpool 25/26. Vermelho reds. Dri-FIT ADV.",
    "badge": "Novo",
    "imgs": ["Liverpool I 25/26_foto1.jpg"]
  },
  {
    "id": 14,
    "nome": "Inter de Milão I 25/26",
    "marca": "nike",
    "tipo": "camisa de time",
    "liga": "Serie A",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Inter de Milão 25/26. Azul e preto nerazzurri.",
    "badge": "",
    "imgs": ["Inter de Milão I 25/26_foto1.jpg"]
  },
  {
    "id": 15,
    "nome": "Bayern München I 25/26",
    "marca": "adidas",
    "tipo": "camisa de time",
    "liga": "Bundesliga",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Bayern München 25/26. Vermelho bávaro.",
    "badge": "",
    "imgs": ["Bayern München I 25/26_foto1.jpg"]
  },
  {
    "id": 16,
    "nome": "PSG I 25/26",
    "marca": "nike",
    "tipo": "camisa de time",
    "liga": "Ligue 1",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular PSG 25/26. Azul marinho parisien.",
    "badge": "Promoção",
    "imgs": ["PSG I 25/26_foto1.jpg"]
  },
  {
    "id": 17,
    "nome": "Brasil I — Copa 2026",
    "marca": "nike",
    "tipo": "camisa de seleção",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Seleção Brasileira Copa 2026. Verde e amarelo canarinho.",
    "badge": "Copa 26",
    "imgs": ["Brasil I — Copa 2026_foto1.jpg"]
  },
  {
    "id": 18,
    "nome": "Brasil II — Copa 2026",
    "marca": "nike",
    "tipo": "camisa de seleção",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa reserva Seleção Brasileira Copa 2026. Azul canarinho.",
    "badge": "Copa 26",
    "imgs": ["Brasil II — Copa 2026_foto1.jpg"]
  },
  {
    "id": 19,
    "nome": "Argentina I — Copa 2026",
    "marca": "adidas",
    "tipo": "camisa de seleção",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Argentina Copa 2026. Listras celeste e branca.",
    "badge": "",
    "imgs": ["Argentina I — Copa 2026_foto1.jpg"]
  },
  {
    "id": 20,
    "nome": "Inglaterra I — Copa 2026",
    "marca": "nike",
    "tipo": "camisa de seleção",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Inglaterra Copa 2026. Branca three lions.",
    "badge": "",
    "imgs": ["Inglaterra I — Copa 2026_foto1.jpg"]
  },
  {
    "id": 21,
    "nome": "França I — Copa 2026",
    "marca": "nike",
    "tipo": "camisa de seleção",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular França Copa 2026. Azul marinho les bleus.",
    "badge": "",
    "imgs": ["França I — Copa 2026_foto1.jpg"]
  },
  {
    "id": 22,
    "nome": "Portugal I — Copa 2026",
    "marca": "nike",
    "tipo": "camisa de seleção",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Camisa titular Portugal Copa 2026. Vermelho e verde.",
    "badge": "",
    "imgs": ["Portugal I — Copa 2026_foto1.jpg"]
  },
  {
    "id": 23,
    "nome": "Nike Air Max 270",
    "marca": "nike",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Amortecimento Max Air. Corrida e casual. Unissex.",
    "badge": "Mais Vendido",
    "imgs": ["Nike Air Max 270_foto1.jpg"]
  },
  {
    "id": 24,
    "nome": "Nike Air Force 1 07",
    "marca": "nike",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Clássico streetwear. Couro premium. Unissex.",
    "badge": "",
    "imgs": ["Nike Air Force 1 07_foto1.jpg"]
  },
  {
    "id": 25,
    "nome": "Nike Revolution 7",
    "marca": "nike",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Corrida entry-level. Leve e respirável. Unissex.",
    "badge": "Custo-Benefício",
    "imgs": ["Nike Revolution 7_foto1.jpg"]
  },
  {
    "id": 26,
    "nome": "Nike Pegasus 41",
    "marca": "nike",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Corrida de performance. Zoom Air. Masculino e feminino.",
    "badge": "Novo",
    "imgs": ["Nike Pegasus 41_foto1.jpg"]
  },
  {
    "id": 27,
    "nome": "Nike Dunk Low",
    "marca": "nike",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Streetwear premium. Várias colaborações. Unissex.",
    "badge": "Collab",
    "imgs": ["Nike Dunk Low_foto1.jpg"]
  },
  {
    "id": 28,
    "nome": "Nike Vomero 18",
    "marca": "nike",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Corrida máximo conforto. ZoomX + React.",
    "badge": "",
    "imgs": ["Nike Vomero 18_foto1.jpg"]
  },
  {
    "id": 29,
    "nome": "Adidas Ultraboost 24",
    "marca": "adidas",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Corrida premium. Boost infinito. Cabedal Primeknit+.",
    "badge": "Mais Vendido",
    "imgs": ["Adidas Ultraboost 24_foto1.jpg"]
  },
  {
    "id": 30,
    "nome": "Adidas Stan Smith",
    "marca": "adidas",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Clássico eterno. Couro vegano. Unissex.",
    "badge": "",
    "imgs": ["Adidas Stan Smith_foto1.jpg"]
  },
  {
    "id": 31,
    "nome": "Adidas Samba OG",
    "marca": "adidas",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Tendência streetwear 2025. Couro premium. Unissex.",
    "badge": "Trend",
    "imgs": ["Adidas Samba OG_foto1.jpg"]
  },
  {
    "id": 32,
    "nome": "Adidas Response CL",
    "marca": "adidas",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Corrida retrô Y2K look. Unissex.",
    "badge": "",
    "imgs": ["Adidas Response CL_foto1.jpg"]
  },
  {
    "id": 33,
    "nome": "Adidas Gazelle Indoor",
    "marca": "adidas",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Retro esportivo. Camurça premium. Unissex.",
    "badge": "Trend",
    "imgs": ["Adidas Gazelle Indoor_foto1.jpg"]
  },
  {
    "id": 34,
    "nome": "Adidas Adizero Boston 12",
    "marca": "adidas",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Corrida longa distância. Lightrike Ultra.",
    "badge": "",
    "imgs": ["Adidas Adizero Boston 12_foto1.jpg"]
  },
  {
    "id": 35,
    "nome": "New Balance 990v6",
    "marca": "new balance",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Made in USA. Premium heritage. Unissex.",
    "badge": "Premium",
    "imgs": ["New Balance 990v6_foto1.jpg"]
  },
  {
    "id": 36,
    "nome": "New Balance 2002R",
    "marca": "new balance",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Retro running icon. ABZORB + N-ergy. Unissex.",
    "badge": "Mais Vendido",
    "imgs": ["New Balance 2002R_foto1.jpg"]
  },
  {
    "id": 37,
    "nome": "New Balance 530",
    "marca": "new balance",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Chunky retro. MRT core. Unissex.",
    "badge": "Trend",
    "imgs": ["New Balance 530_foto1.jpg"]
  },
  {
    "id": 38,
    "nome": "New Balance Fresh Foam X 1080v14",
    "marca": "new balance",
    "tipo": "tênis",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["35", "36", "37", "38", "39", "40", "41", "42", "43", "44"],
    "desc": "Corrida premium máximo conforto. Fresh Foam X.",
    "badge": "",
    "imgs": ["New Balance Fresh Foam X 1080v14_foto1.jpg"]
  },
  {
    "id": 39,
    "nome": "Camiseta Dry-Fit UV50+",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Proteção solar UV50+. Manga curta. Tecido respirável. Masculino.",
    "badge": "Mais Vendido",
    "imgs": ["Camiseta Dry-Fit UV50+_foto1.jpg"]
  },
  {
    "id": 40,
    "nome": "Regata Essential",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Treino e casual. 100% poliéster. Unissex.",
    "badge": "",
    "imgs": ["Regata Essential_foto1.jpg"]
  },
  {
    "id": 41,
    "nome": "Top Esportivo Overlap",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["PP", "P", "M", "G", "GG"],
    "desc": "Academia e praia. Suporte médio. Feminino.",
    "badge": "Novo",
    "imgs": ["Top Esportivo Overlap_foto1.jpg"]
  },
  {
    "id": 42,
    "nome": "Camiseta Oversized",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Casual. Corte amplo. Algodão premium. Unissex.",
    "badge": "",
    "imgs": ["Camiseta Oversized_foto1.jpg"]
  },
  {
    "id": 43,
    "nome": "Short Running 7pol",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Corrida. DryFit. Bolso traseiro. Masculino.",
    "badge": "Mais Vendido",
    "imgs": ["Short Running 7pol_foto1.jpg"]
  },
  {
    "id": 44,
    "nome": "Bermuda Tactel",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Praia e casual. Cordão ajustável. Unissex.",
    "badge": "Promoção",
    "imgs": ["Bermuda Tactel_foto1.jpg"]
  },
  {
    "id": 45,
    "nome": "Short 2-em-1 com Compressão",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Treino e corrida. Inner short compressão. Masculino.",
    "badge": "",
    "imgs": ["Short 2-em-1 com Compressão_foto1.jpg"]
  },
  {
    "id": 46,
    "nome": "Short de Ciclismo",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["PP", "P", "M", "G", "GG"],
    "desc": "Bike e academia. Compressão total. Feminino.",
    "badge": "",
    "imgs": ["Short de Ciclismo_foto1.jpg"]
  },
  {
    "id": 47,
    "nome": "Legging Compressão 7/8",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["PP", "P", "M", "G", "GG"],
    "desc": "Academia e yoga. Cintura alta. 4-way stretch. Feminino.",
    "badge": "Mais Vendido",
    "imgs": ["Legging Compressão 7/8_foto1.jpg"]
  },
  {
    "id": 48,
    "nome": "Calça Jogger Leve",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Casual e treino. Tecido leve. Unissex.",
    "badge": "",
    "imgs": ["Calça Jogger Leve_foto1.jpg"]
  },
  {
    "id": 49,
    "nome": "Macacão Esportivo",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["PP", "P", "M", "G", "GG"],
    "desc": "Praia e treino. All-in-one. Feminino.",
    "badge": "Novo",
    "imgs": ["Macacão Esportivo_foto1.jpg"]
  },
  {
    "id": 50,
    "nome": "Calça com Proteção UV",
    "marca": "sport",
    "tipo": "roupa - verão",
    "liga": "",
    "brl": "Preço sob consulta",
    "eur": "Price on request",
    "sizes": ["P", "M", "G", "GG", "XG"],
    "desc": "Esporte aquático e outdoor. UV50+. Unissex.",
    "badge": "",
    "imgs": ["Calça com Proteção UV_foto1.jpg"]
  }
];