import csv
import io
import json

csv_data = """arquivo_foto_principal,arquivo_foto_2,arquivo_foto_3,nome_produto,marca,tipo,tamanhos,preco_brl,preco_eur,descricao,badge
Jaqueta Carhartt WIP x Sacai Chore Coat Cinza_foto1.jpg,,,Jaqueta Carhartt WIP x Sacai Chore Coat Cinza,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Exclusividade e estilo definem a Jaqueta Carhartt WIP x Sacai Chore Coat na cor cinza. Combinando o utilitarismo clássico da Carhartt com o design de alta moda da Sacai, esta peça apresenta botões dourados, múltiplos bolsos frontais e gola contrastante preta. Perfeita para um visual streetwear sofisticado, resistente e autêntico. Compre agora e eleve seu guarda-roupa com esta colaboração única.",Limitado
Jaqueta Carhartt WIP x Sacai Workwear Marrom_foto1.jpg,,,Jaqueta Carhartt WIP x Sacai Workwear Marrom,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A Jaqueta Carhartt WIP x Sacai Marrom é a fusão perfeita entre moda contemporânea e workwear. Possui fechamento em zíper, gola preta contrastante e detalhes exclusivos de sobreposição na barra, assinatura visual da Sacai. Confeccionada em lona resistente, oferece durabilidade incomparável e um visual urbano de destaque.",Limitado
Jaqueta Carhartt WIP x Sacai Detroit Preta_foto1.jpg,,,Jaqueta Carhartt WIP x Sacai Detroit Preta,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Destaque-se com a Jaqueta Carhartt WIP x Sacai Preta. Esta peça de colaboração exclusiva traz o icônico corte utilitário com acabamentos premium, zíper dourado, bolsos frontais reforçados e um detalhe de forro cinza aparente na barra. Ideal para sobreposições no inverno, unindo atitude e luxo desconstruído.",Limitado
Jaqueta Carhartt WIP Detroit Washed Black_foto1.jpg,,,Jaqueta Carhartt WIP Detroit Washed Black,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"O clássico absoluto do workwear: a Jaqueta Carhartt WIP Detroit em lona estonada (Washed Black). Com gola em veludo cotelê contrastante e bolso no peito com fechamento em zíper, ela garante resistência extrema e um visual autêntico e despojado para o dia a dia. Uma peça essencial de streetwear que nunca sai de moda.",Hot
Jaqueta Corta-Vento Carhartt WIP Tech Bege_foto1.jpg,,,Jaqueta Corta-Vento Carhartt WIP Tech Bege,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Proteção e design moderno se encontram nesta Jaqueta Carhartt WIP Bege. Com tecido técnico de alta performance, gola alta, zíperes selados e detalhes utilitários nas mangas, é a escolha ideal para dias de vento ou chuva na cidade. Combinando funcionalidade com a estética clean, é perfeita para quem busca estilo e utilidade.",
Jaqueta Carhartt WIP Detroit Hamilton Brown_foto1.jpg,,,Jaqueta Carhartt WIP Detroit Hamilton Brown,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Ícone da cultura urbana, a Jaqueta Carhartt WIP Detroit na cor clássica Hamilton Brown é indispensável no seu closet. Feita em lona Dearborn super resistente, conta com gola de veludo cotelê, zíper robusto e a clássica etiqueta da marca no peito. Versátil e extremamente durável, é o investimento perfeito para o seu estilo.",Hot
Jaqueta Carhartt WIP Modular Preta_foto1.jpg,,,Jaqueta Carhartt WIP Modular Preta,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Minimalismo e atitude com a Jaqueta Carhartt WIP Modular Preta. Com um corte limpo, fechamento em zíper frontal dourado e bolsos laterais discretos, ela é a base perfeita para qualquer look. Confeccionada com a qualidade premium da marca, oferece conforto e longevidade para o uso diário, sendo uma peça coringa no guarda-roupa masculino.",
Suéter Carhartt WIP Half-Zip Knit Marinho_foto1.jpg,,,Suéter Carhartt WIP Half-Zip Knit Marinho,carhartt,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Aqueça-se com muito estilo usando o Suéter em Tricô Carhartt WIP Half-Zip Azul Marinho. Apresenta gola alta ajustável com zíper e o logo em destaque bordado no peito. Confeccionado em malha encorpada de alta qualidade, é a opção ideal para um visual casual, confortável e com forte apelo streetwear nos dias mais frios.",Hot
Suéter Carhartt WIP Half-Zip Knit Cinza_foto1.jpg,,,Suéter Carhartt WIP Half-Zip Knit Cinza,carhartt,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Conforto premium e design clássico no Suéter Carhartt WIP Half-Zip Cinza Mescla. Com modelagem confortável, gola alta em zíper e o icônico logo da marca bordado, esta peça de tricô é perfeita para sobreposições elegantes e descontraídas. Une a tradição da marca com as tendências urbanas atuais.",
Jaqueta Carhartt WIP x Sacai Chore Coat Preta_foto1.jpg,,,Jaqueta Carhartt WIP x Sacai Chore Coat Preta,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A Jaqueta Carhartt WIP x Sacai Chore Coat Preta é o ápice do design colaborativo. Unindo a robustez do workwear com detalhes refinados como botões dourados, forro aparente contrastante e modelagem impecável, esta peça eleva o conceito de roupa utilitária. Uma adição poderosa e exclusiva para os fãs de moda high-end e streetwear.",Limitado
Jaqueta Carhartt WIP x Stüssy Detroit Bege_foto1.jpg,,,Jaqueta Carhartt WIP x Stüssy Detroit Bege,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A fusão definitiva entre o autêntico workwear e a cultura skate/surf. A Jaqueta Carhartt WIP x Stüssy Detroit Bege traz o clássico design de lona resistente com gola em veludo cotelê marrom e o bordado icônico da Stüssy no peito, logo acima do clássico bolso de zíper. Uma peça de colecionador, perfeita para um visual urbano exclusivo e cheio de atitude.",Limitado
Jaqueta Carhartt WIP Detroit Denim Azul_foto1.jpg,,,Jaqueta Carhartt WIP Detroit Denim Azul,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"O estilo atemporal do jeans encontra a durabilidade extrema do workwear na Jaqueta Carhartt WIP Detroit Denim. Com lavagem azul clássica e gola contrastante em veludo cotelê caramelo, esta peça oferece versatilidade incomparável para o dia a dia. Conta com o tradicional bolso no peito com zíper e a inconfundível etiqueta Carhartt, sendo um curinga para qualquer guarda-roupa.",Hot
Jaqueta Corta-Vento Carhartt WIP Tech Cinza_foto1.jpg,,,Jaqueta Corta-Vento Carhartt WIP Tech Cinza,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Funcionalidade e estética techwear se unem na Jaqueta Corta-Vento Carhartt WIP Tech Cinza. Desenvolvida com tecido leve e resistente a intempéries, possui gola alta, zíperes frontais selados e bolsos utilitários de design limpo. Ideal para sobreposições técnicas e para manter o estilo impecável mesmo em dias de clima instável na cidade.",
Jaqueta Carhartt WIP Detroit Preta_foto1.jpg,,,Jaqueta Carhartt WIP Detroit Preta,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"O pilar absoluto do guarda-roupa streetwear: a Jaqueta Carhartt WIP Detroit Preta. Confeccionada em lona de algodão robusta com gola em veludo cotelê na mesma cor, ela entrega um visual clean, minimalista e de alta durabilidade. Uma jaqueta essencial, de corte reto e atemporal, que combina com absolutamente qualquer look e resiste ao teste do tempo.",Hot
Jaqueta Carhartt WIP Utility Multi-Pocket Cinza_foto1.jpg,,,Jaqueta Carhartt WIP Utility Multi-Pocket Cinza,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Para quem busca utilitarismo sem abrir mão do design contemporâneo, a Jaqueta Carhartt WIP Utility Cinza é a escolha certa. Inspirada nos uniformes de trabalho tradicionais, apresenta modelagem reta e múltiplos bolsos estratégicos (frontais e na manga), garantindo espaço e funcionalidade. Seu tom neutro facilita a composição de looks modernos e estruturados.",
Jaqueta Corta-Vento Carhartt WIP Tech Preta_foto1.jpg,,,Jaqueta Corta-Vento Carhartt WIP Tech Preta,carhartt,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A Jaqueta Corta-Vento Carhartt WIP Tech Preta é a definição de funcionalidade urbana com sofisticação. Com silhueta ajustada, tecido tecnológico resistente ao vento, gola alta e acabamentos em zíper selado, ela oferece proteção com uma estética ninja/techwear. Uma peça fundamental para navegar a cidade com conforto e uma pegada moderna.",
Moletom BAPE Shark Full Zip Camo Branco e Azul_foto1.jpg,,,Moletom BAPE Shark Full Zip Camo Branco/Azul,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"O ápice do streetwear de luxo. Este Moletom BAPE Full Zip apresenta uma camuflagem exclusiva em tons de branco e cinza com detalhes gráficos em azul. O destaque absoluto fica por conta do icônico capuz ""Shark"" (tubarão) com fechamento total por zíper. Confeccionado em algodão premium, garante um fit estruturado, conforto extremo e presença marcante em qualquer look urbano.",Limitado
Moletom BAPE Shark Full Zip Color Camo Vermelho_foto1.jpg,,,Moletom BAPE Shark Full Zip Color Camo Vermelho,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Impossível passar despercebido com o Moletom BAPE Color Camo Vermelho. Apresentando o clássico padrão de camuflagem da marca (Ape Head camo) em tons vibrantes de vermelho e vinho, esta peça traz o inconfundível capuz Shark com fechamento até o topo. Modelagem impecável e algodão de altíssima gramatura para quem vive e respira a cultura sneakerhead.",Hot
Moletom BAPE Shark Full Zip Color Camo Roxo_foto1.jpg,,,Moletom BAPE Shark Full Zip Color Camo Roxo,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Exclusividade em cada detalhe. O Moletom BAPE Color Camo Roxo funde a camuflagem tradicional da marca com tons de roxo e rosa, criando um visual arrojado e super cobiçado. Conta com o lendário capuz de tubarão (Shark motif) com zíper total, punhos reforçados e caimento perfeito. Uma verdadeira peça de colecionador para elevar seu estilo streetwear.",Hot
Moletom BAPE Shark Full Zip Color Camo Azul_foto1.jpg,,,Moletom BAPE Shark Full Zip Color Camo Azul,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Frescor e atitude com o Moletom BAPE Color Camo Azul. A padronagem icônica da A Bathing Ape ganha vida em tons de azul e marinho nesta peça essencial. O design Full Zip permite fechar a jaqueta até o topo do capuz, revelando o rosto do famoso tubarão. Feito para garantir conforto duradouro e um visual autêntico e inesquecível.",Hot
Moletom BAPE Shark Full Zip Camo Rosa_foto1.jpg,,,Moletom BAPE Shark Full Zip Camo Rosa,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Ousadia em estado puro. Este Moletom BAPE Full Zip destaca-se pela sua camuflagem vibrante em tons de rosa claro e choque. Com o tradicional fechamento em zíper até o topo do capuz Shark, esta peça é um statement fashion imediato. Confeccionada com os melhores materiais japoneses, oferece um toque macio, retenção de calor e durabilidade premium.",Limitado
Moletom BAPE x Neighborhood Half-Zip Preto_foto1.jpg,,,Moletom BAPE x Neighborhood Half-Zip Preto,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Uma colaboração lendária entre dois gigantes do streetwear japonês. O Moletom BAPE x Neighborhood Preto traz um design meio-zíper (half-zip) inovador, com a tipografia conjunta no peito e detalhes sutis de dentes de tubarão na gola interna. Com um corte levemente oversized e algodão denso, é uma peça rara, minimalista e carregada de história da cultura de rua.",Limitado
Moletom BAPE Shark Full Zip Camo Cotton Candy_foto1.jpg,,,Moletom BAPE Shark Full Zip Camo Cotton Candy,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Estética lúdica com o peso do hype. O Moletom BAPE Shark Camo ""Cotton Candy"" combina tons pastéis de azul turquesa e rosa na clássica camuflagem da marca. O fechamento total em zíper e o capuz de tubarão mantêm o DNA autêntico da BAPE. Uma peça vibrante e extremamente exclusiva, perfeita para quebrar a monotonia dos looks de inverno.",Limitado
Moletom BAPE Shark Full Zip Preto_foto1.jpg,Moletom BAPE Shark Full Zip Preto_foto2.jpg,Moletom BAPE Shark Full Zip Preto_foto3.jpg,Moletom BAPE Shark Full Zip Preto,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"O clássico absoluto e essencial do streetwear. O Moletom BAPE Shark Full Zip Preto oferece versatilidade com uma base lisa, destacando os inconfundíveis dentes de tubarão e o design WGM no capuz. Feito em algodão de gramatura pesada, possui o patch Ape Head bordado no peito e fechamento de zíper que vai até o topo. Perfeito para quem busca a assinatura da A Bathing Ape em um visual mais clean e fácil de combinar no dia a dia.",Hot
Moletom BAPE Shark Full Zip Cinza Mescla (Sólido)_foto1.jpg,Moletom BAPE Shark Full Zip Cinza Mescla (Sólido)_foto2.jpg,,Moletom BAPE Shark Full Zip Cinza Mescla (Sólido),Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Conforto premium com a estética inconfundível do hype. Este Moletom BAPE Shark Full Zip em cinza mescla é uma peça curinga para qualquer guarda-roupa urbano. Apresenta o capuz de tubarão com fechamento total e o bordado Ape Head no peito. O tecido estruturado e macio garante durabilidade e um caimento impecável, ideal para sobreposições nos dias mais frios.",Hot
Moletom BAPE Shark Full Zip City Camo_foto1.jpg,,,Moletom BAPE Shark Full Zip City Camo,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"A padronagem ""City Camo"" da BAPE é um marco na cultura de rua. Este moletom Full Zip combina a camuflagem icônica em tons de preto, cinza e branco (com detalhes que brilham no escuro em algumas edições). Com o lendário capuz Shark, esta peça entrega um visual de alto impacto e exclusividade para os fãs mais exigentes de sneakers e moda urbana.",Limitado
Moletom BAPE Shark Full Zip Space Camo_foto1.jpg,,,Moletom BAPE Shark Full Zip Space Camo,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Uma viagem ao espaço com a assinatura da A Bathing Ape. O Moletom BAPE Space Camo apresenta um padrão de camuflagem escuro pontilhado com estrelas e detalhes em azul cósmico. O design Full Zip permite fechar o capuz Shark até o topo, criando uma silhueta inesquecível. Uma peça de destaque absoluto, perfeita para compor looks ousados e exclusivos.",Limitado
Moletom BAPE Shark Full Zip Black-Grey Camo_foto1.jpg,,,Moletom BAPE Shark Full Zip Black/Grey Camo,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Sofisticação e atitude na medida certa. Este moletom BAPE traz a camuflagem Color Camo em tons profundos de preto e cinza escuro, criando um visual mais sóbrio, mas igualmente impressionante. O contraste fica por conta do forro do capuz Shark. Confeccionado com materiais japoneses de altíssima qualidade, oferece luxo e conforto em uma modelagem clássica.",Limitado
Moletom BAPE Shark Full Zip Color Camo Azul Escuro_foto1.jpg,,,Moletom BAPE Shark Full Zip Navy Camo,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"O Moletom BAPE Navy Camo mergulha a tradicional estampa Ape Head em tons intensos de azul escuro e preto. Com punhos contrastantes em azul sólido e o característico capuz Shark Full Zip, esta jaqueta de moletom é um item obrigatório para colecionadores. Estruturada e pesada, garante proteção térmica e um estilo streetwear inigualável.",Limitado
Moletom BAPE x Neighborhood Half-Zip Cinza_foto1.jpg,,,Moletom BAPE x Neighborhood Half-Zip Cinza,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Streetwear de elite. O Moletom BAPE x Neighborhood Cinza mescla a identidade visual de duas potências japonesas em uma peça impecável. O fechamento half-zip revelam o icônico padrão Shark no forro do capuz, enquanto o peito exibe o co-branding exclusivo. Confortável, estruturado e altamente cobiçado, é um investimento certo para curadores de moda urbana.",
Moletom BAPE Shark Full Zip Snow Camo_foto1.jpg,,,Moletom BAPE Shark Full Zip Snow Camo,Bape,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Uma abordagem clean e luxuosa para o streetwear de peso. O Moletom BAPE Shark Full Zip ""Snow Camo"" apresenta a icônica camuflagem Ape Head em tons sutis de branco, cinza claro e creme. O grande destaque é o lendário capuz de tubarão com fechamento total em zíper. Confeccionado em algodão de alta gramatura, oferece um caimento estruturado e conforto premium para quem busca exclusividade e estilo inconfundível nas ruas.",Limitado
Jaqueta Adidas Originals Veludo Cotelê Cinza e Bordô_foto1.jpg,,,Jaqueta Adidas Originals Veludo Cotelê Cinza e Bordô,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A estética retrô elevada ao máximo. Esta jaqueta track jacket da Adidas Originals substitui o tradicional poliéster por um veludo cotelê (corduroy) premium na cor cinza, contrastando com as icônicas três listras em bordô. Gola alta e punhos pretos completam o design vintage. Uma peça sofisticada, texturizada e perfeita para destacar o look urbano nos dias mais frios.",Hot
Moletom Adidas Originals Premium Detalhes Dourados Preto_foto1.jpg,Moletom Adidas Originals Premium Detalhes Dourados Preto_foto2,,Moletom Adidas Originals Premium Detalhes Dourados Preto,Adidas,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"O clássico moletom preto reinventado com toques de luxo. Apresentando as lendárias três listras nas mangas, esta peça se destaca pelos seus detalhes exclusivos: cordões do capuz trançados com acabamento em contas de madeira, botões metálicos dourados nos bolsos e um patch bordado premium no peito. Um item de colecionador que funde o DNA esportivo com uma alfaiataria streetwear refinada.",Limitado
Jaqueta Puffer Adidas x Balenciaga Preta_foto1.jpg,,,Jaqueta Puffer Adidas x Balenciaga Preta,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"O encontro épico entre o streetwear e a alta moda parisiense. A Jaqueta Puffer Adidas x Balenciaga Preta entrega uma silhueta oversized e estruturada, perfeita para o inverno rigoroso. Traz o trefoil da Adidas reimaginado com a tipografia da Balenciaga bordado no peito e as clássicas três listras nos ombros. Uma peça de luxo absoluta, desenhada para quem dita tendências.",Limitado
Camiseta Adidas Performance Halftone Logo Preta_foto1.jpg,,,Camiseta Adidas Performance Halftone Logo Preta,Adidas,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"Minimalismo gráfico com forte impacto visual. Esta camiseta preta de manga curta traz o logo ""Mountain"" da Adidas em uma impressão texturizada estilo halftone (pontilhada) no centro do peito. Confeccionada em algodão macio com modelagem levemente solta (relaxed fit), é a camiseta ideal tanto para treinos quanto para composições urbanas do dia a dia.",
Calça Cargo Adidas Zip Parachute Cinza_foto1.jpg,Calça Cargo Adidas Zip Parachute Cinza_foto2.jpg,,Calça Cargo Adidas Zip Parachute Cinza,Adidas,calças,"P,M,G,GG",Preço sob consulta,Price on request,"O futuro do techwear. Esta calça parachute em nylon cinza esconde um segredo de design incrível: os zíperes frontais, quando abertos, revelam painéis em azul vibrante com as clássicas três listras brancas. Isso permite que você mude a silhueta (de reta para wide/flare) e o visual da calça em segundos. Peça utilitária, altamente interativa e perfeita para a estética Y2K.",Hot
Jaqueta Adidas x Bad Bunny x Mercedes-AMG Quilted_foto1.jpg,Jaqueta Adidas x Bad Bunny x Mercedes-AMG Quilted_foto2.jpg,Jaqueta Adidas x Bad Bunny x Mercedes-AMG Quilted_foto3.jpg,Jaqueta Adidas x Mercedes-AMG Petronas Quilted Preta,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A velocidade das pistas encontra a cultura das ruas. Esta jaqueta acolchoada (quilted) preta é fruto da colaboração com a equipe Mercedes-AMG Petronas de Fórmula 1. Apresenta costuras em grade geométrica, logotipos bordados no peito e detalhes utilitários robustos. Uma outerwear de estética motorsport imponente, quente e extremamente exclusiva.",Limitado
Jaqueta Adidas x Brain Dead Track Top VerdeBege_foto1.jpg,Jaqueta Adidas x Brain Dead Track Top VerdeBege_foto2.jpg,,Jaqueta Adidas x Brain Dead Track Top Verde/Bege (Vista Traseira),Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Arte subversiva no DNA da marca das três listras. A Jaqueta Adidas x Brain Dead funde o estilo clássico das track jackets com o grafismo surreal da marca californiana. A parte traseira exibe um grande painel bege em contraste com o verde-oliva, destacando o logo híbrido da colaboração bordado em grande escala. Ousada, criativa e indispensável para fãs de streetwear independente.",Limitado
Moletom Adidas Originals Premium Detalhes Dourados Vermelho_foto1.jpg,Moletom Adidas Originals Premium Detalhes Dourados Vermelho_foto2.jpg,,Moletom Adidas Originals Premium Detalhes Dourados Vermelho,Adidas,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Uma explosão de cor com acabamentos de alta costura. Este moletom vermelho vibrante traz as icônicas três listras em branco e eleva o padrão com cordões trançados especiais, botões dourados nos bolsos laterais e um patch exclusivo no peito. Confeccionado em algodão pesado de qualidade superior, é a peça ideal para construir um visual marcante, confortável e com muita personalidade.",Hot
Jaqueta Adidas Originals Clássica Preta_foto1.jpg,,,Jaqueta Adidas Originals Clássica Preta,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"O ícone atemporal que definiu gerações. A Jaqueta Track Top Adidas Originals preta é o pilar de qualquer guarda-roupa streetwear. Com as icônicas três listras brancas descendo pelas mangas, gola alta e o logo Trefoil bordado no peito, ela oferece versatilidade infinita. Feita em material leve e durável, transita perfeitamente do esporte para a moda casual.",Hot
Calça Adidas Wide Leg Nylon Chumbo_foto1.jpg,,,Calça Adidas Wide Leg Nylon Chumbo,Adidas,calças,"P,M,G,GG",Preço sob consulta,Price on request,"Conforto contemporâneo com silhueta relaxada. Esta calça em nylon de tom chumbo (cinza escuro) apresenta uma modelagem wide leg (pernas largas) e pregas sutis, criando um visual fluido e moderno. Com cós elástico e tecido tecnológico super leve, é a definição de athleisure sofisticado. Traz um logotipo minimalista na lateral, ideal para looks clean e futuristas.",
Jaqueta Corta-Vento Adidas Zip-Sleeve Cinza_foto1.jpg,Jaqueta Corta-Vento Adidas Zip-Sleeve Cinza_foto2.jpg,,Jaqueta Corta-Vento Adidas Zip-Sleeve Cinza,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Design interativo e visual futurista. Esta jaqueta corta-vento em nylon cinza possui um corte minimalista e limpo na frente, mas os zíperes nas mangas se abrem para revelar um tecido azul vibrante com as icônicas três listras da Adidas. Ideal para criar looks dinâmicos e combinar com a calça da mesma linha, garantindo um visual techwear autêntico e adaptável.",Hot
Calça Adidas Wide Leg Nylon Preta_foto1.jpg,,,Calça Adidas Wide Leg Nylon Preta,Adidas,calças,"P,M,G,GG",Preço sob consulta,Price on request,"Minimalismo e conforto extremo. A Calça Adidas Wide Leg em nylon preto traz a silhueta solta e fluida que dominou o streetwear atual. Super leve e versátil, conta com um pequeno logo bordado na perna e caimento baggy sofisticado. A base perfeita para destacar seus sneakers favoritos em qualquer look do dia a dia.",
Camiseta Adidas Performance Halftone Branca_foto1.jpg,,,Camiseta Adidas Performance Halftone Branca,Adidas,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"Frescor e design gráfico moderno. Esta camiseta branca oversized destaca-se pela estampa do logo ""Mountain"" da Adidas em estilo halftone (pontilhismo) em preto no centro do peito. Confeccionada em algodão premium respirável, oferece um caimento relaxado, sendo a peça essencial para um guarda-roupa casual e esportivo de alto nível.",
Jaqueta Corta-Vento Adidas Asymmetrical Zip Preta_foto1.jpg,,,Jaqueta Corta-Vento Adidas Asymmetrical Zip Preta,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Uma visão avant-garde do sportwear. Esta jaqueta de nylon preta revoluciona o design clássico com um fechamento em zíper assimétrico e detalhes franzidos (ruched) nas laterais, criando uma silhueta única e ajustável. Apresenta um logo inovador no peito que mistura o Trefoil com uma estética cibernética/estrela. Pura atitude para quem dita tendências.",Limitado
Jaqueta Adidas Y2K Racing Cinza_foto1.jpg,,,Jaqueta Adidas Y2K Racing Cinza,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Nostalgia pura dos anos 2000. Inspirada no universo do motocross e nas pistas de corrida, esta jaqueta cinza traz recortes com piping (vivo) branco e maxi tipografia ""adi das"" aplicada no peito, além de logos retrô esportivos. Com silhueta levemente volumosa e elásticos nos punhos, é o item perfeito para dominar a tendência Y2K com muito estilo.",Hot
Adidas Crochet Knit Preta_foto1.jpg,Adidas Crochet Knit Preta_foto2.jpg,,Adidas Crochet Knit Preta,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Textura e ousadia para os dias quentes. Esta jaqueta track top preta inova ao substituir o tecido tradicional por uma malha vazada estilo crochet/mesh. Mantém o DNA da marca com as icônicas três listras brancas nas mangas e o Trefoil bordado no peito, oferecendo um visual respirável, altamente texturizado e perfeito para sobreposições criativas.",Hot
Jaqueta Corta-Vento Adidas Retro Racing_foto1.jpg,,,Jaqueta Corta-Vento Adidas Retro Racing Preta,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A versão all black da cobiçada jaqueta Y2K de motocross. Mantém o design esportivo dos anos 2000 com recortes demarcados por piping branco contrastante e a maxi tipografia ""adi das"" no peito. O tecido leve de nylon e a modelagem volumosa garantem o máximo de estilo streetwear com uma forte pegada nostálgica.",Hot
Calça Adidas Wide Leg NylonCinza Claro_foto1.jpg,,,Calça Adidas Wide Leg Nylon (Cor: Cinza Claro),Adidas,calças,"P,M,G,GG",Preço sob consulta,Price on request,"A terceira cor da nossa calça queridinha do streetwear. Em tom cinza claro, esta calça de nylon wide leg ilumina o look mantendo o caimento fluido e super confortável. Possui cós elástico e um logo minimalista, ideal para destacar seus sneakers favoritos e criar silhuetas modernas e relaxadas no dia a dia.",
Jaqueta Adidas Originals Woven Track Top Preta_foto1.jpg,,,Jaqueta Adidas Originals Woven Track Top Preta,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"O design atemporal das três listras em uma construção super leve. A Jaqueta Woven Track Top na cor preta é confeccionada em nylon estruturado, oferecendo um caimento baggy contemporâneo. Conta com gola alta, zíper frontal e o Trefoil bordado. A peça curinga absoluta para proteger do vento e compor looks urbanos minimalistas.",Hot
Jaqueta Adidas Originals Woven Track Top Cinza Claro_foto1.jpg,,,Jaqueta Adidas Originals Woven Track Top Cinza Claro,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Leveza e versatilidade definem esta Jaqueta Woven Track Top. O tom cinza claro ilumina o visual, enquanto o tecido de nylon garante resistência e um fit impecável. Apresenta a clássica silhueta corta-vento da Adidas Originals com gola alta e listras nos ombros. Perfeita para um estilo athleisure sofisticado e moderno.",
Jaqueta Adidas Originals Woven Track Top Azul Marinho_foto1.jpg,,,Jaqueta Adidas Originals Woven Track Top Azul Marinho,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"A tradição esportiva encontra a moda de rua. Na elegante cor azul marinho com listras em azul claro, esta jaqueta de nylon proporciona uma estética retrô e esportiva. O modelo woven oferece mais estrutura que o poliéster comum, garantindo um visual premium e confortável para a correria da cidade.",
Jaqueta Adidas Originals Veludo Cotelê Bege e Preto_foto1.jpg,,,Jaqueta Adidas Originals Veludo Cotelê Bege e Preto,Adidas,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Elevando o sportswear ao nível da alta costura urbana. Esta jaqueta é confeccionada em veludo cotelê (corduroy) premium na cor bege creme, com gola, punhos e barra em preto contrastante. As três listras pretas nas mangas e o tecido texturizado criam uma estética vintage de luxo, perfeita para quem dita tendências no streetwear.",Hot
Camiseta Adidas Performance Halftone Logo Cinza_foto1.jpg,,,Camiseta Adidas Performance Halftone Logo Cinza,Adidas,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"A terceira e versátil cor da linha oversized que é puro conforto e estilo. A Camiseta Adidas Performance na cor cinza claro destaca o icônico logo ""Mountain"" em estampa halftone (pontilhada) em tom mais escuro no centro do peito. Confeccionada em algodão de toque macio e com modelagem relaxada, é a peça curinga perfeita para elevar seus looks casuais e esportivos com uma estética clean e urbana.",
Moletom Supreme Polartec Fleece Half-Zip - Navy_foto1.jpg,,,Moletom Supreme Polartec Fleece Half-Zip - Navy,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Pullover térmico em fleece Polartec azul marinho com Box Logo frontal centralizado.,badge
Moletom Supreme Polartec Fleece Half-Zip - Black_foto1.jpg,,,Moletom Supreme Polartec Fleece Half-Zip - Black,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Moletom fleece preto básico com tecnologia Polartec e branding Supreme discreto.,
Moletom Supreme Polartec Fleece Half-Zip - Grey_foto1.jpg,,,Moletom Supreme Polartec Fleece Half-Zip - Grey,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Opção cinza mescla do fleece técnico Polartec para o inverno europeu.,
Moletom Supreme Polartec Fleece Half-Zip - Pink_foto1.jpg,,,Moletom Supreme Polartec Fleece Half-Zip - Pink,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Fleece Polartec rosa vibrante. Design funcional com meio-zíper e isolamento térmico.,
Calça Supreme x Umbro Track Pants - Gradient Blue_foto1.jpg,,,Supreme x Umbro Track Pant - Marinho/Cinza,Supreme,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça de agasalho com efeito degradê do marinho para o cinza e logos colaborativos.,
Supreme x Umbro Track Pant ROSA-CINZA_foto1.jpg,,,Supreme x Umbro Track Pant - Rosa/Cinza,Supreme,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça de agasalho com efeito degradê do rosa para o cinza e logos colaborativos.,
Supreme Rhinestone Hoodie Marinho_foto1.jpg,,,Supreme Rhinestone Hoodie - Marinho,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Moletom com capuz marinho e logotipo Supreme em strass prateado.,
Supreme Rhinestone Hoodie preto_foto1.jpg,,,Supreme Rhinestone Hoodie - Preto,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Moletom com capuz preto e logotipo Supreme em strass vermelho.,Hot
Jaqueta Supreme x Nike Corduroy Hooded - Black_foto1.jpg,,,Jaqueta Supreme x Nike Corduroy Hooded - Black,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta de veludo cotelê Nike x Supreme. Ângulo traseiro com logos bordados em arco.,Hot
Supreme x Ducati Track Jacket_foto1.jpg,Supreme x Ducati Track Jacket_foto2.jpg,,Jaqueta Supreme x Ducati Track Jacket - Preto/Cinza,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Jaqueta de corrida com logos de patrocinadores (Shell, Pirelli, Brembo) e ""Supreme 1"" nas costas.",Hot
Supreme Small Box Tee preto_foto1.jpg,,,Camiseta Supreme Small Box Tee - Preto,Supreme,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta de algodão preta com mini logotipo Supreme no peito.,Limitado
Jaqueta Supreme x Vanson Leathers GORE-TEX - Black_foto1.jpg,,,Jaqueta Supreme x Vanson Leathers GORE-TEX - Black,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta racing de alta performance com tecnologia GORE-TEX e patches bordados Supreme.,
Jaqueta Supreme x Vanson Leathers GORE-TEX - Grey-Yellow_foto1.jpg,Jaqueta Supreme x Vanson Leathers GORE-TEX - Grey-Yellow_foto2.jpg,,Jaqueta Supreme x Vanson Leathers GORE-TEX - Grey/Yellow,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Colaboração premium em cinza e amarelo. Foto frontal destacando patches e detalhes técnicos.,Limitado
Jaqueta Supreme x Vanson Leathers GORE-TEX - Blue-Green_foto1.jpg,Jaqueta Supreme x Vanson Leathers GORE-TEX - Blue-Green_foto2.jpg,,Jaqueta Supreme x Vanson Leathers GORE-TEX - Blue/Green,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta técnica racing em tons de azul e verde. Ângulo traseiro com estrela e logo Supreme.,Limitado
Calça Supreme x Umbro Track Pants - Gradient Blue_foto1.jpg,,,Calça Supreme x Umbro Track Pants - Gradient Blue,Supreme,calças,"P,M,G,GG",Preço sob consulta,Price on request,"Calça esportiva em nylon com degradê, parte do conjunto Supreme x Umbro.",Hot
Jaqueta Supreme x Umbro Leather Track - Navy_foto1.jpg,,,Jaqueta Supreme x Umbro Leather Track - Navy,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta de treino em couro azul marinho com detalhes contrastantes em branco.,Hot
Jaqueta Supreme x Umbro Leather Track - Black_foto1.jpg,,,Jaqueta Supreme x Umbro Leather Track - Black,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Design minimalista em couro preto Supreme x Umbro para um look urbano sofisticado.,
Jaqueta Supreme Almighty Varsity - Navy-White_foto1.jpg,Jaqueta Supreme Almighty Varsity - Navy-White_foto2.jpg,,Jaqueta Supreme Almighty Varsity - Navy/White,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta Varsity clássica com corpo em lã azul e mangas em couro. Patches Almighty Supreme.,
Jaqueta Supreme Almighty Varsity - Black_foto1.jpg,Jaqueta Supreme Almighty Varsity - Black_foto2.jpg,,Jaqueta Supreme Almighty Varsity - Black,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Versão monocromática da jaqueta Almighty com patches contrastantes em branco.,Limitado
Jaqueta Supreme x Ducati V4 Track - Grey-Red_foto1.jpg,Jaqueta Supreme x Ducati V4 Track - Grey-Red_foto2.jpg,,Jaqueta Supreme x Ducati V4 Track - Grey/Red,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Collab exclusiva com a Ducati. Ângulo traseiro com número 1 e branding oficial Shell.,Limitado
Jaqueta Supreme Windbreaker - Grey_foto1.jpg,Jaqueta Supreme Windbreaker - Grey_foto2.jpg,,Jaqueta Supreme Windbreaker - Grey,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Quebra-vento leve cinza com tipografia gótica nas costas. Essencial para o dia a dia.,Limitado
Moletom Supreme Box Logo Crewneck - Red -Washed-_foto1.jpg,,,Moletom Supreme Box Logo Crewneck - Red (Washed),Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Clássico Box Logo Supreme com lavagem vintage tonal. Item de colecionador.,
Moletom Supreme Box Logo Crewneck - White_foto1.jpg,,,Moletom Supreme Box Logo Crewneck - White,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,O icônico Box Logo vermelho sobre algodão pesado branco. Peça central Mirage.,Limitado
Moletom Supreme Box Logo Crewneck - Navy_foto1.jpg,,,Moletom Supreme Box Logo Crewneck - Navy,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Box Logo clássico em azul marinho profundo. Qualidade premium e corte Hypebeast.,Limitado
Moletom Supreme Box Logo Crewneck - Acid Black_foto1.jpg,,,Moletom Supreme Box Logo Crewneck - Acid Black,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Versão especial com lavagem ácida (acid wash) do tradicional Box Logo.,Limitado
Moletom Supreme Textured Sweater - Black_foto1.jpg,,,Moletom Supreme Textured Sweater - Black,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Suéter de malha texturizada com logo Supreme bordado em arco no peito.,Limitado
Moletom Supreme Glitter Hoodie - Pink_foto1.jpg,,,Moletom Supreme Glitter Hoodie - Pink,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Hoodie rosa com o logo Supreme em aplicação de brilho (glitter) para destaque visual.,Hot
Camiseta Supreme Small Box Logo - White_foto1.jpg,,,Camiseta Supreme Small Box Logo - White,Supreme,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta em algodão premium branco com o minimalista Small Box Logo no peito.,Hot
Camiseta Supreme Small Box Logo - Grey_foto1.jpg,,,Camiseta Supreme Small Box Logo - Grey,Supreme,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Versão cinza clássica da t-shirt básica com o selo Small Box da marca.,
Jersey Supreme x Marithe Francois Girbaud - Black_foto1.jpg,,,Jersey Supreme x Marithe Francois Girbaud - Black,Supreme,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Jersey de mesh estilo hóquei com logo tipo grafite. Estética streetwear anos 90.,
Moletom Supreme Knitted Polo - Black_foto1.jpg,,,Moletom Supreme Knitted Polo - Black,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Polo de manga longa em tricô preto. O encontro do streetwear com o casual chic.,Limitado
Jaqueta Supreme Quilted Bomber - Black_foto1.jpg,,,Jaqueta Supreme Quilted Bomber - Black,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Bomber jacket com padrão matelassê (quilted) e detalhes em zíper metálico.,
Moletom Supreme Camo Half-Snap Fleece_foto1.jpg,,,Moletom Supreme Camo Half-Snap Fleece,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Fleece com estampa camuflada urbana e botões de pressão na gola.,
Moletom Supreme Fleece Half-Snap Preto_foto1.jpg,,,Moletom Supreme Fleece Half-Snap - Black,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Pullover em fleece preto com gola interna em padrão camuflado e fecho de pressão.,
Jaqueta Supreme Technical Pullover - Navy_foto1.jpg,,,Jaqueta Supreme Technical Pullover - Navy,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta técnica em nylon azul com patches heráldicos e tipografia Supreme.,Hot
Jaqueta Supreme x Umbro Track Jacket - Gradient Blue_foto1.jpg,,,Jaqueta Supreme x Umbro Track Jacket - Gradient Blue,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta de treino Umbro com efeito degradê em tons de azul e logo Supreme Champions. Estilo retro sport de alta performance.,Hot
Jaqueta Supreme x Umbro Track Jacket - Gradient Navy_foto1.jpg,,,Jaqueta Supreme x Umbro Track Jacket - Gradient Navy,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta de treino Umbro com efeito degradê do marinho profundo para o cinza. Inclui logo Supreme Champions e estética esportiva clássica.,Hot
Camiseta Supreme x Marithé François Girbaud Jersey Branca_foto1.jpg,,,Camiseta Supreme x Marithé François Girbaud Jersey - Branca,Supreme,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"Jersey em mesh branco com tipografia estilo graffiti no centro, mangas longas e listras em azul marinho.",Limitado
Camiseta Supreme Small Box Logo Marinho_foto1.jpg,,,Camiseta Supreme Small Box Logo - Marinho,Supreme,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"Confeccionada em algodão de gramatura premium, traz o icônico ""Bogo"" em versão mini no peito. Visual clean e versátil",
Fleece Supreme x The North Face RTG Preto_foto1.jpg,Fleece Supreme x The North Face RTG Preto_foto2.jpg,,Fleece Supreme x The North Face RTG - Preto,Supreme,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Camada técnica encorpada da linha Remote Terrain Gear com design tático, capuz funcional estilo balaclava e co-branding bordado. ",Limitado
Suéter Supreme Arc Logo Chenille - Creme _foto1.jpg,,,Suéter Supreme Arc Logo Chenille - Creme ,Supreme,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,,
4ac1e8ee.jpg,7fb25575.jpg,,Moletom Supreme x Nike Air Max Zip Hoodie - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Moletom com zíper frontal e o icônico Swoosh gigante nas costas, detalhe 'Air Max' na barra e bordado Supreme no capuz.",Limitado
2658d595.jpg,a5c50b66.jpg,,Moletom Supreme x Nike Air Max Zip Hoodie - White,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Versão branca premium da colaboração Air Max, com acabamentos contrastantes em preto e branding exclusivo.",Limitado
23a1f8b9.jpg,2533c130.jpg,,Moletom Supreme x Nike Air Max Zip Hoodie - Heather Grey,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Peça em cinza mescla com o design técnico da linha Air Max e logotipos colaborativos aplicados.,Limitado
7739565b.jpg,,,Jaqueta Nike x Nocta x L'Art de L'Automobile Racing Jacket,nike,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Jaqueta de corrida exclusiva em tons de azul e amarelo, com patches bordados de patrocinadores e branding Nocta.",Limitado
8c269f9e.jpg,871057bc.jpg,,Jaqueta Nike x Nocta Track Jacket - Purple,nike,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta de agasalho técnica em roxo profundo com recortes em lilás e detalhes refletivos Nocta.,Limitado
2d3be1da.jpg,,,Jaqueta Nike x Nocta Track Jacket - Black/Yellow,nike,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Design esportivo clássico Nocta em preto com recortes amarelos vibrantes e tecido técnico respirável.,Limitado
52a57eb3.jpg,,,Jaqueta Nike x Nocta Track Jacket - Grey,nike,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Versão em cinza escuro da linha Nocta, focada em performance e estética streetwear minimalista.",Limitado
3a94b5e6.jpg,,,Jaqueta Nike Denim Trucker Jacket - Light Wash,nike,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,"Jaqueta jeans clássica com lavagem clara, botões metálicos e logotipo Nike bordado no peito.",
54f5841b.jpg,,,Moletom Nike x Skepta Sk Air Tech Hoodie - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Edição especial Tech Fleece em colaboração com Skepta, apresentando detalhes e logos em rose gold.",Limitado
bbdadaf3.jpg,,,Calça Nike x Skepta Sk Air Tech Pants - Black,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,"Calça técnica combinando com o hoodie Skepta, com bolsos selados e branding SK Air exclusivo.",Limitado
0f2ea658.jpg,,,Moletom Nike x Stüssy Crewneck - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Suéter clássico em algodão preto com os logotipos bordados da Stüssy e Nike no peito.,Limitado
3ac38d45.jpg,,,Moletom Nike x Stüssy Crewneck - Grey,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Moletom crewneck cinza mescla da collab Stüssy, ideal para um visual casual e confortável.",Limitado
6b0fc47a.jpg,,,Moletom Nike x Stüssy Pullover Hoodie - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Hoodie básico com capuz, bolso canguru e branding colaborativo Nike x Stüssy.",Limitado
18fb7991.jpg,,,Moletom Nike x Stüssy Pullover Hoodie - Grey,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Hoodie cinza premium com silhueta relaxada e os logos icônicos no peito.,Limitado
09be9640.jpg,,,Moletom Nike x Stüssy Zip-up Hoodie - Grey,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"Versão com zíper frontal do moletom Stüssy, permitindo versatilidade no uso diário.",Limitado
4d7847a3.jpg,,,Moletom Nike x Stüssy Zip-up Hoodie - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Hoodie preto com zíper e bordado colaborativo Stüssy x Nike no peito.,Limitado
a8e7530e.jpg,,,Calça Nike x Stüssy Sweatpants - Grey,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,"Calça de moletom cinza com ajuste elástico e logo colaborativo, parte do conjunto Stüssy.",Limitado
8bf013aa.jpg,,,Calça Nike x Stüssy Sweatpants - Black,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça de moletom preta básica com branding Nike x Stüssy para um conjunto completo.,Limitado
3ddfc16d.jpg,,,Calça Nike x Stüssy Nylon Pants - Tan,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça de nylon leve em tom bege (tan) com bolsos táticos e logo discreto Stüssy.,Limitado
30c5a6f9.jpg,3163e568.jpg,,Camiseta Nike x Palace Tri-Ferg Tee - White,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta branca com o famoso logo Tri-Ferg da Palace atravessado pelo Swoosh da Nike em verde neon.,Limitado
6b614a56.jpg,2b8c97ac.jpg,,Camiseta Nike x Palace Tri-Ferg Tee - Black,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"Versão preta da collab Palace, com estampa Tri-Ferg em destaque nas costas e peito.",Limitado
42136823.jpg,8d6b79ab.jpg,,Camiseta Nike x Palace Tri-Ferg Tee - Grey,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta cinza com grafismos Palace x Nike em amarelo neon para alto impacto visual.,Limitado
287e8fb2.jpg,,,Camiseta Nike x Palace Osaka Tee - White,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"Camiseta da série City da colaboração Palace, homenageando Osaka com tipografia clássica.",Limitado
384b827e.jpg,,,Camiseta Nike x Palace New York Tee - Grey,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Edição New York da collab Palace x Nike em cinza com letras em estilo colegial.,Limitado
3e213515.jpg,,,Camiseta Nike x Palace Tokyo Tee - Pink,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,"Camiseta rosa vibrante da série Tokyo da Palace, fundindo a estética das duas marcas.",Limitado
535c07f0.jpg,,,Camiseta Nike x Palace Seoul Tee - Brown,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Versão marrom da camiseta Seoul com tipografia contrastante em pêssego/laranja.,Limitado
aa3b5184.jpg,,,Camiseta Nike x Palace Seoul Tee - Navy,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta azul marinho da série Seoul com logos colaborativos em azul claro.,Limitado
397e8e41.jpg,33130443.jpg,,Camiseta Nike ACG 'Pocket Guide' Tee - Black,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta ACG com gráfico 'Pocket Guide to Make a Perfect Cup of Coffee' nas costas.,Hot
4f0d0b07.jpg,,,Camiseta Nike ACG Logo Tee - White,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta branca básica da linha All Conditions Gear com logotipo triangular clássico.,Hot
40e0e6a7.jpg,,,Moletom Nike Tech Fleece Full-Zip - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,"O icônico moletom Tech Fleece com isolamento leve, bolsos selados e silhueta aerodinâmica.",Hot
0b39c3c0.jpg,,,Moletom Nike Tech Fleece Full-Zip - Grey,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,A clássica cor cinza do Tech Fleece com detalhes em preto nos zíperes e branding.,Hot
58b07426.jpg,,,Moletom Nike Tech Fleece Full-Zip - Light Blue,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Versão em azul claro pastel do casaco técnico mais desejado da Nike.,Hot
1833761c.jpg,,,Moletom Nike Tech Fleece Hoodie - Black/Yellow,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Moletom Tech Fleece preto com detalhe contrastante do Swoosh em amarelo vibrante.,Hot
33303ab4.jpg,,,Calça Nike Tech Fleece Sweatpants - Grey,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça ajustada com bolso lateral grande e tecido térmico leve para conforto absoluto.,Hot
bc10a829.jpg,,,Moletom Nike Pullover Hoodie - Taupe,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Hoodie básico em tom terra (taupe) com pequeno Swoosh centralizado no peito.,
afb41d2d.jpg,,,Moletom Supreme x Nike Pullover Hoodie - Black Sleeve Logo,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Moletom com capuz e logotipos colaborativos Supreme x Nike aplicados ao longo da manga.,Limitado
15ed18a2.jpg,,,Calça Nike Cargo Trousers - Black,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça utilitária em tecido resistente com múltiplos bolsos laterais cargo e logo discreto.,
6511927e.jpg,,,Calça Nike x Nocta Track Pants - Purple,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça esportiva Nocta em roxo com punhos elásticos e branding refletivo.,Limitado
bf038cbb.jpg,,,Moletom Supreme x Nike Sleeve Logo Hoodie - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Moletom com capuz apresentando logotipia vertical 'NIKE' e 'SUPREME' na manga com Swoosh vermelho bordado.,Limitado
bf2630e6.jpg,,,Camiseta Nike x Kobe Bryant Mamba - White,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Homenagem ao Black Mamba com o logotipo icônico de Kobe Bryant no peito em contraste sobre o branco.,Limitado
c705b117.jpg,,,Camiseta Nike x Kobe Bryant Mamba - Black,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Versão preta da camiseta Mamba Mentality com o logotipo de Kobe Bryant em branco.,Limitado
c51d7a3a.jpg,,,Jaqueta Nike x Nocta Track Jacket - Black,nike,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta técnica de agasalho da linha Nocta em preto com logo Swoosh branco e branding minimalista.,Limitado
eed67489.jpg,,,Calça Nike x Nocta Track Pants - Black,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça de nylon técnica combinando com a jaqueta Nocta,oferecendo conforto e estilo utilitário.
c9b521db.jpg,,,Calça Nike x Stüssy International Sweatpants - Black,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,"Calça de moletom preta com os logos colaborativos e a lista de cidades mundiais (NY, LA, Tokyo, London, Paris).",Limitado
feaccf69.jpg,,,Calça Nike x Stüssy Sweatpants - Grey,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,Calça de moletom cinza mescla com o logotipo retangular Stüssy x Nike na perna.,Limitado
fe13b502.jpg,,,Moletom Nike x Stüssy Crewneck - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Suéter de gola redonda preto com o logotipo retangular exclusivo da colaboração Nike x Stüssy.,Limitado
f2537931.jpg,,,Moletom Nike x Stüssy Crewneck - Grey,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Suéter de gola redonda cinza mescla com o logotipo retangular colaborativo bordado no peito.,Limitado
cdb6fe61.jpg,,,Camiseta Nike x Palace Tri-Ferg - Charcoal (Costas),nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta cinza chumbo apresentando o enorme logo Tri-Ferg da Palace com Swoosh neon nas costas.,Limitado
f1318ff2.jpg,,,Camiseta Nike x Palace Tri-Ferg - Grey,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Camiseta cinza com o logotipo colaborativo Palace x Nike em destaque no peito.,Limitado
f32d9b2d.jpg,,,Camiseta Nike ACG 'Pocket Guide' Tee - White,nike,camisetas,"P,M,G,GG",Preço sob consulta,Price on request,Estampa traseira 'Pocket Guide to Make a Perfect Cup of Coffee' com estética de acampamento retrô.,Hot
f691e7cf.jpg,,,Moletom Nike Tech Fleece Full-Zip - Light Blue,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta Tech Fleece em azul claro pastel com zíper total e design aerodinâmico característico.,Hot
f52bdb7c.jpg,,,Calça Nike Tech Fleece Sweatpants - Black,nike,calças,"P,M,G,GG",Preço sob consulta,Price on request,A clássica calça técnica Tech Fleece preta com bolso lateral selado e ajuste slim.,Hot
e315ff73.jpg,,,Jaqueta Nike Life Insulated Bomber - Black,nike,jaquetas,"P,M,G,GG",Preço sob consulta,Price on request,Jaqueta bomber robusta com gola de couro texturizado e isolamento térmico premium.,
cbc29dc2.jpg,,,Moletom Nike Sportswear Full-Zip Hoodie - Black,nike,Moletons,"P,M,G,GG",Preço sob consulta,Price on request,Moletom com capuz e zíper básico em preto,essencial para composições casuais diárias."""

import urllib.parse

base_url = "https://pub-9eb15062e53d4ad1a85362ac330e3002.r2.dev/"

produtos = []
with io.StringIO(csv_data) as f:
    reader = csv.DictReader(f)
    for i, row in enumerate(reader):
        imgs = []
        for img_key in ['arquivo_foto_principal', 'arquivo_foto_2', 'arquivo_foto_3']:
            v = row.get(img_key, '').strip()
            if v:
                imgs.append(base_url + urllib.parse.quote(v))
        
        sizes = [s.strip() for s in row.get('tamanhos', '').split(',') if s.strip()]
        
        produto = {
            "id": i + 1,
            "nome": row['nome_produto'].strip(),
            "marca": row['marca'].strip().lower(),
            "tipo": row['tipo'].strip().lower(),
            "brl": 1890,
            "eur": 348,
            "sizes": sizes,
            "desc": row['descricao'].strip(),
            "badge": row['badge'].strip() if row.get('badge') else "",
            "imgs": imgs
        }
        produtos.append(produto)

js_content = "/* ─── PRODUTOS MIRAGE CO. ─────────────────────────────────────────────────── */\n"
js_content += "window.todos = " + json.dumps(produtos, ensure_ascii=False, indent=2) + ";\n"

with open("produtos.js", "w", encoding="utf-8") as f:
    f.write(js_content)

print(f"Updated produtos.js with {len(produtos)} products.")
